/**
 * data.ts — All seed data. Contains zero logic.
 *
 * To add a new company:
 *   1. Add its ID to the C object
 *   2. Append a record to COMPANIES
 *   3. Append timeline entries to TIMELINE
 *   4. Append relationship rows to COMPANY_IMPLEMENTATION_PATTERNS and COMPANY_PROBLEMS
 *
 * To add a new problem, solution pattern, or implementation pattern:
 *   Follow the same pattern — add ID, append record, append join rows.
 *
 * Run the seeder: set -a && source .env.local && set +a && npx tsx src/db/seeder.ts
 */

import type {
  NewCompany,
  NewCompanyTimeline,
  NewProblem,
  NewSolutionPattern,
  NewImplementationPattern,
  NewBoundaryCase,
} from "./schema";
import {
  companyImplementationPatterns,
  companyProblems,
  solutionPatternProblems,
} from "./schema";

// ─────────────────────────────────────────────────────────────────────────────
// STABLE IDs
// Never change these after first insertion.
// ─────────────────────────────────────────────────────────────────────────────

export const P = {
  wageCompliance:    "a0000001-0000-0000-0000-000000000001",
  employeeBenefits:  "a0000001-0000-0000-0000-000000000002",
  crossBorderEmploy: "a0000001-0000-0000-0000-000000000003",
  itProvisioning:    "a0000001-0000-0000-0000-000000000004",
} as const;

export const SP = {
  payrollInfra:      "b0000001-0000-0000-0000-000000000001",
  cloudHcm:          "b0000001-0000-0000-0000-000000000002",
  globalEmployment:  "b0000001-0000-0000-0000-000000000003",
  compoundWorkforce: "b0000001-0000-0000-0000-000000000004",
} as const;

export const IP = {
  bureau:           "c0000001-0000-0000-0000-000000000001",
  smbSaaS:          "c0000001-0000-0000-0000-000000000002",
  enterpriseHcm:    "c0000001-0000-0000-0000-000000000003",
  complianceFree:   "c0000001-0000-0000-0000-000000000004",
  compoundPlatform: "c0000001-0000-0000-0000-000000000005",
  globalEor:        "c0000001-0000-0000-0000-000000000006",
} as const;

export const C = {
  adp:       "d0000001-0000-0000-0000-000000000001",
  paychex:   "d0000001-0000-0000-0000-000000000002",
  paycom:    "d0000001-0000-0000-0000-000000000003",
  paylocity: "d0000001-0000-0000-0000-000000000004",
  workday:   "d0000001-0000-0000-0000-000000000005",
  gusto:     "d0000001-0000-0000-0000-000000000006",
  zenefits:  "d0000001-0000-0000-0000-000000000007",
  rippling:  "d0000001-0000-0000-0000-000000000008",
  justworks: "d0000001-0000-0000-0000-000000000009",
  bamboohr:  "d0000001-0000-0000-0000-000000000010",
  papaya:    "d0000001-0000-0000-0000-000000000011",
  deel:      "d0000001-0000-0000-0000-000000000012",
  remote:    "d0000001-0000-0000-0000-000000000013",
  oyster:    "d0000001-0000-0000-0000-000000000014",
  sap:       "d0000001-0000-0000-0000-000000000015",
  oracle:    "d0000001-0000-0000-0000-000000000016",
} as const;

// ─────────────────────────────────────────────────────────────────────────────
// PROBLEMS
// ─────────────────────────────────────────────────────────────────────────────

export const PROBLEMS: NewProblem[] = [
  {
    id: P.wageCompliance,
    statement: "Businesses cannot calculate, withhold, and disburse employee wages while remaining compliant with tax and labour regulations.",
    lifecycle: "mature",
    notes: "Status quo: manual calculation + paper cheques + accountant. Underlying constraint: regulatory friction + coordination failure. Frequency: bi-weekly. Urgency: high (legal obligation with penalties for non-compliance).",
  },
  {
    id: P.employeeBenefits,
    statement: "Businesses cannot provide employees with competitive benefits packages without the purchasing power of large employers.",
    lifecycle: "mature",
    notes: "Status quo: direct insurer negotiation (only viable at scale) or no benefits offered. Underlying constraint: scale requirements. SMBs cannot access group rates without aggregation.",
  },
  {
    id: P.crossBorderEmploy,
    statement: "Companies cannot legally employ workers in foreign jurisdictions without establishing local legal entities, which takes 12-18 months and significant capital.",
    lifecycle: "growing",
    notes: "Status quo: contractor misclassification (legally risky) or entity setup (slow, expensive). Underlying constraint: regulatory friction per jurisdiction. Accelerated by remote work normalisation post-2020.",
  },
  {
    id: P.itProvisioning,
    statement: "Businesses cannot provision or deprovision employee access to software, hardware, and corporate systems as a single coordinated action.",
    lifecycle: "growing",
    notes: "Status quo: manual IT tickets + email + spreadsheets per system. Underlying constraint: coordination failure. Security risk on offboarding is significant driver.",
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// SOLUTION PATTERNS
// Winning/failure conditions are included here.
// Seeder uses onConflictDoUpdate for these fields — data.ts is the source of truth.
// ─────────────────────────────────────────────────────────────────────────────

export const SOLUTION_PATTERNS: NewSolutionPattern[] = [
  {
    id: SP.payrollInfra,
    name: "Payroll processing infrastructure",
    firstObserved: 1949,
    patternDurability: "decades-old",
    winningCondition: "Regulatory complexity creates recurring non-discretionary demand for compliance execution, and the rate of regulatory change keeps that complexity high enough that specialist knowledge cannot be cost-effectively replicated in-house.",
    failureCondition: "Regulatory complexity stabilises or decreases to the point where in-house compliance execution becomes cheaper than specialist outsourcing, or a general-purpose software platform successfully abstracts the compliance layer at a price below specialist outsourcing cost.",
    winningConditionMaturity: "proposed",
    winningConditionValidFrom: 1949,
    notes: "Has produced profitable operators across three distinct technological eras: manual bureau, desktop/server, cloud SaaS. 8 grounding observations. Maturity: proposed — all observations in same industry. Upgrades to established when confirmed in tax filing, healthcare billing, or legal compliance.",
  },
  {
    id: SP.cloudHcm,
    name: "Cloud HCM platform",
    firstObserved: 2005,
    patternDurability: "established",
    winningCondition: "Incumbent's installed-base lock-in prevents it from offering cloud delivery without cannibalising existing licence revenue, creating a durable opening for a cloud-native entrant whose cost structure carries no on-premise installed base to protect.",
    failureCondition: "Incumbent successfully completes cloud transition — via acquisition, rebuild, or partner ecosystem — before the cloud-native entrant reaches sufficient scale, closing the cost structure window before the entrant achieves switching-cost parity.",
    winningConditionMaturity: "proposed",
    winningConditionValidFrom: 2005,
    notes: "3 grounding observations (Workday, SAP, Oracle) all profitable. 100% profitable confirmation rate. Upgrades to established when confirmed in adjacent domains (accounting software, CRM, ERP).",
  },
  {
    id: SP.globalEmployment,
    name: "Global employment infrastructure",
    firstObserved: 2016,
    patternDurability: "emerging",
    notes: "Two sub-approaches: entity-ownership model (Deel, Remote) vs. partner model (Papaya). Entity-ownership appears to be winning. 4 observations, 0 profitable. Winning/failure conditions deferred — no profitable confirmation yet.",
  },
  {
    id: SP.compoundWorkforce,
    name: "Compound workforce management platform",
    firstObserved: 2016,
    patternDurability: "emerging",
    notes: "Single observation (Rippling). Winning/failure conditions deferred — needs 2+ observations. Parker Conrad's explicit thesis: unified employee record enabling cross-functional automation at near-zero marginal cost per new module.",
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// IMPLEMENTATION PATTERNS
// ─────────────────────────────────────────────────────────────────────────────

export const IMPLEMENTATION_PATTERNS: NewImplementationPattern[] = [
  {
    id: IP.bureau,
    name: "Manual payroll bureau",
    solutionPatternId: SP.payrollInfra,
    firstObserved: 1949,
    status: "live",
    businessModel: "Per-employee-per-period fee (outsourced service)",
    pricingSignal: "<100/mo",
    notes: "Offline service model. Initial advantage: batch processing at scale employers could not achieve. Moat: switching cost from embedded payroll data + compliance records. Mechanism: delegation. Status quo displaced: in-house manual payroll.",
  },
  {
    id: IP.smbSaaS,
    name: "Cloud-native SMB payroll SaaS",
    solutionPatternId: SP.payrollInfra,
    firstObserved: 1998,
    status: "live",
    businessModel: "Per-employee-per-month subscription",
    pricingSignal: "<100/mo",
    notes: "Self-serve web-based payroll for 1-500 employees. Business model convergence confirmed: every surviving operator uses PEPM subscription. Mechanism: abstraction. Status quo displaced: ADP/Paychex bureau model + QuickBooks desktop.",
  },
  {
    id: IP.enterpriseHcm,
    name: "Cloud enterprise HCM platform",
    solutionPatternId: SP.cloudHcm,
    firstObserved: 2005,
    status: "live",
    businessModel: "Enterprise subscription (annual contract)",
    pricingSignal: "enterprise",
    notes: "Cloud-first replacement for on-premise HCM (PeopleSoft, SAP R/3) targeting Fortune 500. Initial advantage: single-version cloud model vs. on-premise maintenance burden. Mechanism: abstraction. Status quo displaced: Oracle PeopleSoft, SAP on-premise.",
  },
  {
    id: IP.complianceFree,
    name: "Compliance-led free HR SaaS (broker revenue model)",
    solutionPatternId: SP.payrollInfra,
    firstObserved: 2013,
    status: "dead",
    businessModel: "Insurance broker commissions (software free to employer)",
    pricingSignal: "free",
    notes: "DEAD PATTERN. Structural failure: requires operating as a licensed insurance broker in each state, which cannot scale at venture speed. Zenefits was the only instantiation. Mechanism: abstraction + regulatory arbitrage.",
  },
  {
    id: IP.compoundPlatform,
    name: "Compound HR + IT + Finance platform",
    solutionPatternId: SP.compoundWorkforce,
    firstObserved: 2016,
    status: "live",
    businessModel: "Modular per-employee-per-month subscription",
    pricingSignal: "<100/mo",
    notes: "Unified workforce OS built on single employee record (Employee Graph) powering HR, IT, Finance. New modules reach $1M ARR within 5-6 months of launch because data setup is already complete. Mechanism: workflow orchestration + abstraction. Capability required: unified data architecture from day one.",
  },
  {
    id: IP.globalEor,
    name: "Global payroll / Employer of Record platform",
    solutionPatternId: SP.globalEmployment,
    firstObserved: 2016,
    status: "live",
    businessModel: "Per-employee-per-month ($500-650 for EOR, lower for contractor)",
    pricingSignal: "<100/mo",
    notes: "Two sub-models: entity-ownership (Deel, Remote — own legal entities per country, stronger moat) vs. partner model (Papaya — local providers, faster expansion, weaker moat). Entity-ownership appears to be winning. Status quo displaced: traditional EOR agencies charging 15%+ of payroll. Mechanism: coordination.",
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// COMPANIES
// ─────────────────────────────────────────────────────────────────────────────

export const COMPANIES: NewCompany[] = [
  {
    id: C.adp,
    name: "Automatic Data Processing (ADP)",
    founded: 1949,
    country: "USA",
    status: "operating",
    stage: "public",
    fundingHistory: "Self-funded from founding. IPO September 1961 at $3/share. Nasdaq: ADP.",
    revenueSignal: ">1B",
    profitabilitySignal: "known_profitable",
    evidenceWeight: "strong_validator",
    signalConfidence: "high",
    notableFacts: "FY2025 revenue $20.6B, net income $4.08B (public filing). Processes payroll for ~1 in 6 US employees. 75 years operating. Founded by Henry Taub with $6,000.",
  },
  {
    id: C.paychex,
    name: "Paychex, Inc.",
    founded: 1971,
    country: "USA",
    status: "operating",
    stage: "public",
    fundingHistory: "Self-funded from founding. Tom Golisano started with $3,000. IPO 1983 (Nasdaq: PAYX).",
    revenueSignal: ">1B",
    profitabilitySignal: "known_profitable",
    evidenceWeight: "strong_validator",
    signalConfidence: "high",
    notableFacts: "FY2025 revenue $5.57B, net income $1.66B (public filing). ~800,000 payroll clients. Focused on SMB segment vs. ADP full-market coverage.",
  },
  {
    id: C.paycom,
    name: "Paycom Software, Inc.",
    founded: 1998,
    country: "USA",
    status: "operating",
    stage: "public",
    fundingHistory: "Self-funded until IPO April 2014 (NYSE: PAYC). No external VC.",
    revenueSignal: ">1B",
    profitabilitySignal: "known_profitable",
    evidenceWeight: "strong_validator",
    signalConfidence: "high",
    notableFacts: "2025 revenue $2.05B, operating income $567M (public filing). One of the first fully online payroll providers. Bootstrapped to IPO.",
  },
  {
    id: C.paylocity,
    name: "Paylocity Holding Corporation",
    founded: 1997,
    country: "USA",
    status: "operating",
    stage: "public",
    fundingHistory: "Founded as Ameripay Payroll Ltd. Self-funded until IPO 2014 (Nasdaq: PCTY). Founder Steve Sarowitz held 44% at IPO.",
    revenueSignal: ">1B",
    profitabilitySignal: "known_profitable",
    evidenceWeight: "strong_validator",
    signalConfidence: "high",
    notableFacts: "2025 revenue $1.59B, operating income $304M (public filing). Targets SMB-mid market 50-1,000 employees. Active acquirer: BeneFLEX (2018), Blue Marble Payroll (2021), Airbase (2024).",
  },
  {
    id: C.workday,
    name: "Workday, Inc.",
    founded: 2005,
    country: "USA",
    status: "operating",
    stage: "public",
    fundingHistory: "Greylock Partners (initial VC). IPO October 2012 at ~$9.5B valuation (Nasdaq: WDAY).",
    revenueSignal: ">1B",
    profitabilitySignal: "known_profitable",
    evidenceWeight: "strong_validator",
    signalConfidence: "high",
    notableFacts: "FY2026 revenue $9.55B, net income $693M (public filing). Founded by David Duffield and Aneel Bhusri after Oracle acquired PeopleSoft. Serves 50%+ of Fortune 500.",
  },
  {
    id: C.gusto,
    name: "Gusto (formerly ZenPayroll)",
    founded: 2012,
    country: "USA",
    status: "operating",
    stage: "unicorn",
    fundingHistory: "Seed $6.1M 2012 (YC). Total ~$746M across 9 rounds. Tender offer June 2025 at $9.3B valuation.",
    revenueSignal: ">100M",
    profitabilitySignal: "unknown",
    evidenceWeight: "weak_validator",
    signalConfidence: "low",
    notableFacts: "Sacra estimates $975M revenue 2025. 500,000+ businesses. US-only — geographic constraint creates documented international demand gap. Accountant referral channel is primary GTM.",
  },
  {
    id: C.zenefits,
    name: "Zenefits (acquired by TriNet)",
    founded: 2013,
    country: "USA",
    status: "acquired",
    stage: "series_c",
    fundingHistory: "$598M total. Series A led by a16z. Series C $500M at $4.5B valuation (2015 peak).",
    revenueSignal: "<10M",
    profitabilitySignal: "known_unprofitable",
    evidenceWeight: "disconfirming",
    signalConfidence: "high",
    notableFacts: "DISCONFIRMING CASE. Fatal failure: selling insurance without licences in multiple states. Parker Conrad resigned 2016. Mass layoffs. $598M raised, $4.5B peak valuation, complete value destruction. Parker Conrad then founded Rippling as the corrected implementation. Acquired by TriNet ~2023.",
  },
  {
    id: C.rippling,
    name: "Rippling People Center, Inc.",
    founded: 2016,
    country: "USA",
    status: "operating",
    stage: "unicorn",
    fundingHistory: "Seed $7M 2016 (YC + Initialized). Series G $450M May 2025 ($16.8B). Total ~$1.85B across 10 rounds.",
    revenueSignal: ">100M",
    profitabilitySignal: "unknown",
    evidenceWeight: "weak_validator",
    signalConfidence: "low",
    notableFacts: "Sacra estimates $570M ARR February 2025. 20,000+ customers. 99.5% annual retention. 10+ product lines each >$1M ARR within 5-6 months of launch. Founded by Parker Conrad (ex-Zenefits) as the corrected compound platform implementation. Anticipated IPO 2026.",
  },
  {
    id: C.justworks,
    name: "Justworks, Inc.",
    founded: 2012,
    country: "USA",
    status: "operating",
    stage: "series_e",
    fundingHistory: "$148M total. Index Ventures, FirstMark, Redpoint. Series E $50M 2020. Formerly Clockwork Solutions.",
    revenueSignal: ">100M",
    profitabilitySignal: "unknown",
    evidenceWeight: "weak_validator",
    signalConfidence: "low",
    notableFacts: "Latka estimates $350M revenue 2024. 12,000 customers. $1.4B valuation 2025. PEO model — co-employment within the US.",
  },
  {
    id: C.bamboohr,
    name: "BambooHR",
    founded: 2008,
    country: "USA",
    status: "operating",
    stage: "bootstrapped",
    fundingHistory: "Minimal. Single round from Norwest Venture Partners. Primarily bootstrapped.",
    revenueSignal: ">100M",
    profitabilitySignal: "estimated_profitable_proxy",
    profitabilityProxyApplied: true,
    evidenceWeight: "strong_validator",
    signalConfidence: "low",
    notableFacts: "Growjo estimates ~$358M revenue 2024. 34,000+ organizations, ~2M employees. Bootstrapped 15+ years. Proxy rule applied. Started with HRIS then added payroll — opposite of competitors.",
  },
  {
    id: C.papaya,
    name: "Papaya Global",
    founded: 2016,
    country: "Israel",
    status: "operating",
    stage: "series_d",
    fundingHistory: "$446M total. Series D $250M 2021 ($3.7B peak valuation). Bessemer, Insight, Scale VP, Workday Ventures.",
    revenueSignal: ">100M",
    profitabilitySignal: "unknown",
    evidenceWeight: "weak_validator",
    signalConfidence: "low",
    notableFacts: "Latka estimates $145M revenue 2024. Partner model (vs. entity-ownership): uses local providers rather than owning entities per country. Faster expansion, weaker moat. Valuation compressed from $3.7B 2021 peak.",
  },
  {
    id: C.deel,
    name: "Deel (formerly Lifeslice)",
    founded: 2019,
    country: "USA",
    status: "operating",
    stage: "unicorn",
    fundingHistory: "YC 2019. Total $980M+. Series E $300M October 2025 at $17.3B valuation (Ribbit, Coatue, a16z).",
    revenueSignal: ">100M",
    profitabilitySignal: "unknown",
    evidenceWeight: "weak_validator",
    signalConfidence: "low",
    notableFacts: "Category leader in global EOR/payroll as of 2025. Entity-ownership model. Only company to complete full trajectory: contractors to EOR to global payroll to full HR suite. Launched US payroll 2024. Acquired Safeguard Global enterprise payroll division 2025.",
  },
  {
    id: C.remote,
    name: "Remote Technology, Inc.",
    founded: 2019,
    country: "Estonia",
    status: "operating",
    stage: "series_c",
    fundingHistory: "$496M total. Series C $300M (SoftBank Vision Fund 2). Accel, Sequoia, Index, Two Sigma.",
    revenueSignal: "10-100M",
    profitabilitySignal: "unknown",
    evidenceWeight: "weak_validator",
    signalConfidence: "low",
    notableFacts: "$3B+ valuation. Entity-ownership model. Founded as fully distributed company. Enterprise customers: GitLab, DoorDash.",
  },
  {
    id: C.oyster,
    name: "Oyster HR",
    founded: 2020,
    country: "USA",
    status: "operating",
    stage: "series_b",
    fundingHistory: "$224M total raised 2020-2022.",
    revenueSignal: "<10M",
    profitabilitySignal: "unknown",
    evidenceWeight: "weak_validator",
    signalConfidence: "low",
    notableFacts: "Global HR + payroll + employment in 120+ currencies. Targets larger multinational companies. Founded at exact moment of COVID-driven remote work acceleration.",
  },
  {
    id: C.sap,
    name: "SAP SE",
    founded: 1972,
    country: "Germany",
    status: "operating",
    stage: "public",
    fundingHistory: "Self-funded from founding. IPO 1998 (NYSE: SAP, XETRA: SAP). Founded by five ex-IBM engineers.",
    revenueSignal: ">1B",
    profitabilitySignal: "known_profitable",
    evidenceWeight: "strong_validator",
    signalConfidence: "high",
    notableFacts: "FY2024 revenue EUR 33.3B (~$36B), operating profit EUR 3.9B (public filing). Entered cloud HCM via acquisition of SuccessFactors 2012 for $3.4B. SAP R/3 on-premise installed base was both competitive advantage and liability during cloud transition — illustrates the cloud HCM winning condition directly.",
  },
  {
    id: C.oracle,
    name: "Oracle Corporation",
    founded: 1977,
    country: "USA",
    status: "operating",
    stage: "public",
    fundingHistory: "Self-funded by Larry Ellison, Bob Miner, Ed Oates. IPO March 1986 (Nasdaq: ORCL).",
    revenueSignal: ">1B",
    profitabilitySignal: "known_profitable",
    evidenceWeight: "strong_validator",
    signalConfidence: "high",
    notableFacts: "FY2025 revenue $56.9B, operating income $12.7B (public filing). Hostile acquisition of PeopleSoft 2005 for $10.3B directly triggered Workday's founding. Acquired Taleo (cloud talent mgmt) 2012 for $1.9B. Oracle Fusion HCM launched 2013 — 8 years after PeopleSoft acquisition.",
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// COMPANY TIMELINE
// ─────────────────────────────────────────────────────────────────────────────

export const TIMELINE: NewCompanyTimeline[] = [

  // ADP
  { companyId: C.adp, year: 1949, eventType: "founding",
    implementationPatternId: IP.bureau, problemId: P.wageCompliance,
    description: "Founded as Automatic Payrolls, Inc. Manual payroll processing for local NJ businesses. Capital: $6,000.",
    source: "FundingUniverse company history" },
  { companyId: C.adp, year: 1957, eventType: "product_launch",
    implementationPatternId: IP.bureau,
    description: "Renamed to Automatic Data Processing. Adopted punch-card machines and mainframe computers.",
    source: "TrendSpider / company history" },
  { companyId: C.adp, year: 1961, eventType: "funding",
    description: "IPO at $3/share. ~200 payroll clients. $419k revenue, $25k net profit.",
    source: "FundingUniverse company history" },
  { companyId: C.adp, year: 1990, eventType: "market_entry",
    implementationPatternId: IP.bureau, problemId: P.crossBorderEmploy,
    description: "Launched Employer Services International. Began global expansion. Now operates in 140+ countries.",
    capabilityDeployed: "Payroll compliance expertise and regulatory relationships built across 40+ years of US operations — transferred to international compliance.",
    source: "TrendSpider / companieshistory.com" },

  // Paychex
  { companyId: C.paychex, year: 1971, eventType: "founding",
    implementationPatternId: IP.bureau, problemId: P.wageCompliance,
    description: "Founded by Tom Golisano with $3,000 in Rochester, NY. Targeted SMBs underserved by ADP.",
    source: "Wikipedia" },
  { companyId: C.paychex, year: 1983, eventType: "funding",
    description: "IPO (Nasdaq: PAYX). Previously consolidated 18 franchises in 1979.",
    source: "Wikipedia" },
  { companyId: C.paychex, year: 2000, eventType: "product_launch",
    implementationPatternId: IP.bureau, problemId: P.employeeBenefits,
    description: "Expanded to benefits administration, HR administration, and time & attendance.",
    capabilityDeployed: "Existing employer relationships and payroll processing infrastructure — enabled upsell of adjacent services to existing clients.",
    source: "Wikipedia / Paychex product history" },

  // Paycom
  { companyId: C.paycom, year: 1998, eventType: "founding",
    implementationPatternId: IP.smbSaaS, problemId: P.wageCompliance,
    description: "Founded by Chad Richison in Oklahoma City as one of the first fully online payroll providers. No external funding.",
    source: "Wikipedia" },
  { companyId: C.paycom, year: 2001, eventType: "product_launch",
    implementationPatternId: IP.smbSaaS, problemId: P.wageCompliance,
    description: "Expanded to include HR management modules.",
    capabilityDeployed: "Existing employer database and self-serve web infrastructure.",
    source: "Wikipedia" },
  { companyId: C.paycom, year: 2014, eventType: "funding",
    description: "IPO on NYSE (PAYC). Self-funded to IPO — no venture capital.",
    source: "Wikipedia / SEC filing" },

  // Paylocity
  { companyId: C.paylocity, year: 1997, eventType: "founding",
    implementationPatternId: IP.smbSaaS, problemId: P.wageCompliance,
    description: "Founded as Ameripay Payroll, Ltd. by Steve Sarowitz in Illinois. Online payroll for SMB-mid market.",
    source: "Wikipedia" },
  { companyId: C.paylocity, year: 2014, eventType: "funding",
    description: "IPO (Nasdaq: PCTY). Founder held 44% at IPO.",
    source: "Wikipedia" },
  { companyId: C.paylocity, year: 2021, eventType: "acquisition",
    implementationPatternId: IP.smbSaaS, problemId: P.crossBorderEmploy,
    description: "Acquired Blue Marble Payroll — international payroll services.",
    capabilityDeployed: "Existing SMB payroll infrastructure and customer relationships.",
    capabilityAcquired: "International payroll processing and local compliance relationships via Blue Marble.",
    source: "Wikipedia" },

  // Workday
  { companyId: C.workday, year: 2005, eventType: "founding",
    implementationPatternId: IP.enterpriseHcm, problemId: P.wageCompliance,
    description: "Founded by David Duffield and Aneel Bhusri after Oracle acquired PeopleSoft. Thesis: rebuild enterprise HR on cloud with single-version delivery.",
    source: "companieshistory.com" },
  { companyId: C.workday, year: 2012, eventType: "funding",
    description: "IPO (Nasdaq: WDAY) at ~$9.5B valuation.",
    source: "companieshistory.com / Forbes" },
  { companyId: C.workday, year: 2018, eventType: "acquisition",
    problemId: P.wageCompliance,
    description: "Acquired Adaptive Insights for $1.55B — added enterprise financial planning.",
    capabilityDeployed: "Enterprise customer relationships and unified workforce data model.",
    capabilityAcquired: "Enterprise performance management and financial planning (EPM) via Adaptive Insights.",
    source: "companieshistory.com" },
  { companyId: C.workday, year: 2025, eventType: "product_launch",
    implementationPatternId: IP.enterpriseHcm,
    description: "AI platform repositioning. 8.5% workforce reduction. Acquired Paradox (conversational AI recruiting).",
    source: "companieshistory.com / SEC filings" },

  // Gusto
  { companyId: C.gusto, year: 2012, eventType: "founding",
    implementationPatternId: IP.smbSaaS, problemId: P.wageCompliance,
    description: "Founded as ZenPayroll by Joshua Reeves, Tomer London, Edward Kim. YC batch 2012. Seed $6.1M.",
    source: "Sacra / Built In" },
  { companyId: C.gusto, year: 2014, eventType: "product_launch",
    implementationPatternId: IP.smbSaaS, problemId: P.employeeBenefits,
    description: "Renamed Gusto. Added health insurance benefits administration.",
    capabilityDeployed: "Existing employer database and payroll compliance infrastructure.",
    source: "Sacra / marketcurve.substack.com" },
  { companyId: C.gusto, year: 2020, eventType: "product_launch",
    problemId: P.wageCompliance,
    description: "Launched Gusto Cash Accounts — employee financial wellness. First move into financial services.",
    capabilityDeployed: "Direct banking relationship with 300k+ employees via payroll direct deposit.",
    source: "marketcurve.substack.com" },
  { companyId: C.gusto, year: 2021, eventType: "acquisition",
    problemId: P.crossBorderEmploy,
    description: "Acquired RemoteTeam. Added international contractor payments. Launched Gusto Embedded Payroll API.",
    capabilityDeployed: "Payroll compliance engine and employer relationships.",
    capabilityAcquired: "International contractor management and API-first architecture.",
    source: "marketcurve.substack.com" },

  // Zenefits
  { companyId: C.zenefits, year: 2013, eventType: "founding",
    implementationPatternId: IP.complianceFree, problemId: P.wageCompliance,
    description: "Founded by Parker Conrad and Laks Srini. Free HR software funded by insurance broker commissions.",
    source: "Contrary Research / Fox News" },
  { companyId: C.zenefits, year: 2015, eventType: "funding",
    description: "Series C $500M at $4.5B valuation. 10,000+ businesses, 48 states.",
    source: "Fox News / Entrepreneur" },
  { companyId: C.zenefits, year: 2016, eventType: "pivot",
    description: "FAILURE. Regulatory investigation: selling insurance without licences. Parker Conrad resigned. Mass layoffs. Structural failure of IP-004 confirmed.",
    source: "Contrary Research / Tracxn" },
  { companyId: C.zenefits, year: 2023, eventType: "acquisition",
    description: "Acquired by TriNet. $598M raised, $4.5B peak valuation — complete value destruction.",
    source: "Tracxn" },

  // Rippling
  { companyId: C.rippling, year: 2016, eventType: "founding",
    implementationPatternId: IP.compoundPlatform, problemId: P.wageCompliance,
    description: "Founded by Parker Conrad (ex-Zenefits) and Prasanna Sankar. Seed $7M. Thesis: Employee Graph enabling one-click hire across payroll, benefits, devices, and app access.",
    source: "Sacra / businessmodelcanvastemplate.com" },
  { companyId: C.rippling, year: 2020, eventType: "product_launch",
    implementationPatternId: IP.compoundPlatform, problemId: P.itProvisioning,
    description: "Series B $145M ($1.35B valuation). Expanded into IT management and corporate spend.",
    capabilityDeployed: "Employee Graph — unified employee record already contained app permissions and device data, making IT module launch at near-zero marginal cost.",
    source: "businessmodelcanvastemplate.com / Sacra" },
  { companyId: C.rippling, year: 2022, eventType: "market_entry",
    implementationPatternId: IP.globalEor, problemId: P.crossBorderEmploy,
    description: "Launched global payroll (October 2022). First direct competition with Deel and Remote.",
    capabilityDeployed: "Employee Graph with existing compliance and HR infrastructure — made international payroll a configuration rather than a rebuild.",
    source: "Contrary Research" },
  { companyId: C.rippling, year: 2025, eventType: "funding",
    description: "Series G $450M at $16.8B valuation. $570M ARR. 10+ product lines each >$1M ARR. Super Bowl ad. Anticipated IPO 2026.",
    source: "Sacra / Rainmaker Securities" },

  // Justworks
  { companyId: C.justworks, year: 2012, eventType: "founding",
    implementationPatternId: IP.smbSaaS, problemId: P.wageCompliance,
    description: "Founded as Clockwork Solutions by Isaac Oates and Iris Ramos. Pivoted to PEO model — co-employment for US SMBs.",
    source: "Tracxn" },
  { companyId: C.justworks, year: 2020, eventType: "funding",
    description: "Series E $50M. 12,000+ customers. $1.4B valuation 2025.",
    source: "Latka / Tracxn" },

  // BambooHR
  { companyId: C.bamboohr, year: 2008, eventType: "founding",
    implementationPatternId: IP.smbSaaS, problemId: P.wageCompliance,
    description: "Founded in Utah. Initial product: cloud HRIS for SMBs. Started with HR records, not payroll — opposite of competitors.",
    source: "Software Report / BambooHR site" },
  { companyId: C.bamboohr, year: 2015, eventType: "product_launch",
    implementationPatternId: IP.smbSaaS, problemId: P.wageCompliance,
    description: "Added US payroll. 25,000+ organizations, 2M+ employees across 100 countries.",
    capabilityDeployed: "Existing employee data model and employer relationships — payroll added as natural extension of existing HR record.",
    source: "Software Report" },

  // Papaya Global
  { companyId: C.papaya, year: 2016, eventType: "founding",
    implementationPatternId: IP.globalEor, problemId: P.crossBorderEmploy,
    description: "Founded in Tel Aviv by Eynat Guez, Ruben Drong, Ofer Herman. Cloud-based global payroll via partner model.",
    source: "TechCrunch / BusinessWire" },
  { companyId: C.papaya, year: 2020, eventType: "funding",
    description: "Series B $40M (Scale VP lead). Workday Ventures participated. 300% YoY growth.",
    source: "TechCrunch" },
  { companyId: C.papaya, year: 2021, eventType: "product_launch",
    implementationPatternId: IP.globalEor,
    description: "Series D $250M at $3.7B valuation. Launched Total Payroll — global payroll through single panel.",
    source: "BusinessWire" },

  // Deel
  { companyId: C.deel, year: 2019, eventType: "founding",
    implementationPatternId: IP.globalEor, problemId: P.crossBorderEmploy,
    description: "Founded as Lifeslice by Alex Bouaziz, Shuo Wang, Ofer Simon. YC 2019. Initial product: contractor payment for international workers.",
    source: "Contrary Research" },
  { companyId: C.deel, year: 2021, eventType: "product_launch",
    implementationPatternId: IP.globalEor,
    description: "Expanded from contractors to EOR to global payroll. COVID-driven demand. Entity-ownership model: owns legal entities in each country.",
    capabilityDeployed: "Early entity-ownership infrastructure and contractor payment rails — enabled natural expansion to EOR then payroll.",
    source: "Sacra / Contrary Research" },
  { companyId: C.deel, year: 2024, eventType: "market_entry",
    implementationPatternId: IP.smbSaaS, problemId: P.wageCompliance,
    description: "Launched US payroll. First in-house US payroll engine. Direct competition with Gusto and Rippling.",
    capabilityDeployed: "Global payroll compliance engine and EOR infrastructure — US payroll simpler than multi-country.",
    source: "Contrary Research" },
  { companyId: C.deel, year: 2025, eventType: "acquisition",
    description: "Acquired Safeguard Global enterprise payroll division (March 2025). Series E $300M at $17.3B valuation.",
    capabilityAcquired: "Enterprise payroll customer relationships and contracts via Safeguard Global.",
    source: "Sacra / employborderless.com" },

  // Remote
  { companyId: C.remote, year: 2019, eventType: "founding",
    implementationPatternId: IP.globalEor, problemId: P.crossBorderEmploy,
    description: "Founded in Estonia as a fully distributed company. Initial product: international payroll, benefits, compliance. Entity-ownership model from day one.",
    source: "Contrary Research" },
  { companyId: C.remote, year: 2020, eventType: "product_launch",
    description: "Built own legal entities in each country rather than partnering. Slower but creates stronger moat.",
    capabilityAcquired: "Per-country legal entity ownership and local compliance expertise — primary moat of entity-ownership model.",
    source: "Contrary Research" },
  { companyId: C.remote, year: 2021, eventType: "funding",
    description: "Series C $300M (SoftBank Vision Fund 2). $3B+ valuation. Enterprise customers: GitLab, DoorDash.",
    source: "Contrary Research" },

  // Oyster
  { companyId: C.oyster, year: 2020, eventType: "founding",
    implementationPatternId: IP.globalEor, problemId: P.crossBorderEmploy,
    description: "Global employment in 120+ currencies. Added recruitment and benefits on top of standard EOR.",
    source: "Contrary Research" },
  { companyId: C.oyster, year: 2022, eventType: "funding",
    description: "Raised $224M total across multiple rounds 2020-2022.",
    source: "Contrary Research" },

  // SAP
  { companyId: C.sap, year: 1972, eventType: "founding",
    description: "Founded as Systemanalyse und Programmentwicklung by five ex-IBM engineers in Weinheim, Germany. First client: ICI.",
    source: "SAP company history / Wikipedia" },
  { companyId: C.sap, year: 1992, eventType: "product_launch",
    description: "Launched SAP R/3 — client-server enterprise software. Became dominant on-premise ERP globally. This installed base later created lock-in liability during cloud transition.",
    source: "SAP company history / Wikipedia" },
  { companyId: C.sap, year: 2012, eventType: "acquisition",
    implementationPatternId: IP.enterpriseHcm, problemId: P.wageCompliance,
    description: "Acquired SuccessFactors for $3.4B — cloud HCM provider founded 2001. Primary cloud HCM entry. Workday had demonstrated cloud HCM was viable; SAP could not cloud-ify R/3 HR without disrupting installed base.",
    capabilityDeployed: "SAP global enterprise sales relationships — SuccessFactors got immediate access to SAP 300,000+ customers.",
    capabilityAcquired: "Cloud-native HCM architecture and SaaS delivery model via SuccessFactors.",
    source: "SAP press release / Bloomberg" },
  { companyId: C.sap, year: 2023, eventType: "product_launch",
    implementationPatternId: IP.enterpriseHcm,
    description: "SAP SuccessFactors serves 10,000+ customers in 200 countries. 75%+ of new business is cloud. ~22% enterprise HCM market share.",
    source: "SAP Annual Report 2023 / Gartner HCM Magic Quadrant" },

  // Oracle
  { companyId: C.oracle, year: 1977, eventType: "founding",
    description: "Founded as Software Development Laboratories by Larry Ellison, Bob Miner, Ed Oates. First product: Oracle Database.",
    source: "Oracle company history / Wikipedia" },
  { companyId: C.oracle, year: 2005, eventType: "acquisition",
    description: "Hostile acquisition of PeopleSoft for $10.3B after 18-month battle. PeopleSoft was dominant on-premise HCM vendor. This directly triggered Workday's founding: David Duffield and Aneel Bhusri founded Workday in 2005 as a direct response.",
    capabilityAcquired: "PeopleSoft enterprise HCM customer base, HR domain expertise, and sales relationships.",
    source: "New York Times / Oracle press release" },
  { companyId: C.oracle, year: 2012, eventType: "acquisition",
    implementationPatternId: IP.enterpriseHcm, problemId: P.wageCompliance,
    description: "Acquired Taleo for $1.9B — cloud talent management. First meaningful cloud HCM product.",
    capabilityAcquired: "Cloud-native talent management and recruiting capability via Taleo.",
    source: "Oracle press release / TechCrunch" },
  { companyId: C.oracle, year: 2013, eventType: "product_launch",
    implementationPatternId: IP.enterpriseHcm,
    description: "Launched Oracle Fusion HCM (now Oracle HCM Cloud) — cloud-native rebuild of on-premise HR. 8 years after PeopleSoft acquisition. Gap illustrates execution difficulty of incumbent cloud transition.",
    capabilityDeployed: "PeopleSoft HR domain knowledge and Oracle enterprise infrastructure — reapplied to cloud architecture.",
    source: "Oracle press release / Gartner" },
  { companyId: C.oracle, year: 2024, eventType: "product_launch",
    description: "Oracle HCM Cloud serves 30M+ users across 175+ countries. ~18% HCM market share. FY2025 cloud revenue $21.8B, up 25% YoY.",
    source: "Oracle FY2025 earnings / IDC HCM market share report" },
];

// ─────────────────────────────────────────────────────────────────────────────
// JOIN TABLES
// ─────────────────────────────────────────────────────────────────────────────

type CIP = typeof companyImplementationPatterns.$inferInsert;
type CP  = typeof companyProblems.$inferInsert;
type SPP = typeof solutionPatternProblems.$inferInsert;

export const COMPANY_IMPLEMENTATION_PATTERNS: CIP[] = [
  { companyId: C.adp,       implementationPatternId: IP.bureau,           source: "Wikipedia / companieshistory.com" },
  { companyId: C.paychex,   implementationPatternId: IP.bureau,           source: "Wikipedia" },
  { companyId: C.paycom,    implementationPatternId: IP.smbSaaS,          source: "Wikipedia" },
  { companyId: C.paylocity, implementationPatternId: IP.smbSaaS,          source: "Wikipedia" },
  { companyId: C.workday,   implementationPatternId: IP.enterpriseHcm,    source: "companieshistory.com / SEC filings" },
  { companyId: C.gusto,     implementationPatternId: IP.smbSaaS,          source: "Sacra / Built In" },
  { companyId: C.zenefits,  implementationPatternId: IP.complianceFree,   source: "Contrary Research",
    confidence: "high", notes: "DISCONFIRMING. Only known instantiation of IP-004. Pattern recorded as dead." },
  { companyId: C.rippling,  implementationPatternId: IP.compoundPlatform, source: "Sacra / Rainmaker Securities" },
  { companyId: C.justworks, implementationPatternId: IP.smbSaaS,          source: "Latka / Tracxn",
    notes: "PEO variant — co-employment model, not standard subscription." },
  { companyId: C.bamboohr,  implementationPatternId: IP.smbSaaS,          source: "Software Report" },
  { companyId: C.papaya,    implementationPatternId: IP.globalEor,        source: "TechCrunch / BusinessWire",
    notes: "Partner model (not entity-ownership). Distinct sub-approach within IP-006." },
  { companyId: C.deel,      implementationPatternId: IP.globalEor,        source: "Sacra / Contrary Research" },
  { companyId: C.remote,    implementationPatternId: IP.globalEor,        source: "Contrary Research" },
  { companyId: C.oyster,    implementationPatternId: IP.globalEor,        source: "Contrary Research" },
  { companyId: C.sap,       implementationPatternId: IP.enterpriseHcm,    source: "SAP Annual Report 2023",
    notes: "Entered via acquisition (SuccessFactors, 2012) not organic build. Incumbent transition path." },
  { companyId: C.oracle,    implementationPatternId: IP.enterpriseHcm,    source: "Oracle FY2025 earnings / Taleo acquisition",
    notes: "Entered via acquisition (Taleo, 2012) + internal rebuild (Fusion HCM, 2013). Second incumbent transition path." },
];

export const COMPANY_PROBLEMS: CP[] = [
  { companyId: C.adp,       problemId: P.wageCompliance },
  { companyId: C.adp,       problemId: P.crossBorderEmploy },
  { companyId: C.paychex,   problemId: P.wageCompliance },
  { companyId: C.paychex,   problemId: P.employeeBenefits },
  { companyId: C.paycom,    problemId: P.wageCompliance },
  { companyId: C.paylocity, problemId: P.wageCompliance },
  { companyId: C.paylocity, problemId: P.crossBorderEmploy,
    confidence: "medium", notes: "Blue Marble acquisition 2021 — partial coverage." },
  { companyId: C.workday,   problemId: P.wageCompliance },
  { companyId: C.gusto,     problemId: P.wageCompliance },
  { companyId: C.gusto,     problemId: P.employeeBenefits },
  { companyId: C.gusto,     problemId: P.crossBorderEmploy,
    confidence: "medium", notes: "RemoteTeam acquisition 2021 — contractor-only, not full EOR." },
  { companyId: C.zenefits,  problemId: P.wageCompliance },
  { companyId: C.zenefits,  problemId: P.employeeBenefits },
  { companyId: C.rippling,  problemId: P.wageCompliance },
  { companyId: C.rippling,  problemId: P.employeeBenefits },
  { companyId: C.rippling,  problemId: P.itProvisioning },
  { companyId: C.rippling,  problemId: P.crossBorderEmploy },
  { companyId: C.justworks, problemId: P.wageCompliance },
  { companyId: C.justworks, problemId: P.employeeBenefits },
  { companyId: C.bamboohr,  problemId: P.wageCompliance },
  { companyId: C.papaya,    problemId: P.crossBorderEmploy },
  { companyId: C.deel,      problemId: P.crossBorderEmploy },
  { companyId: C.deel,      problemId: P.wageCompliance,
    confidence: "medium", notes: "US payroll launched 2024." },
  { companyId: C.remote,    problemId: P.crossBorderEmploy },
  { companyId: C.oyster,    problemId: P.crossBorderEmploy },
  { companyId: C.sap,       problemId: P.wageCompliance },
  { companyId: C.oracle,    problemId: P.wageCompliance },
];

export const SOLUTION_PATTERN_PROBLEMS: SPP[] = [
  { solutionPatternId: SP.payrollInfra,      problemId: P.wageCompliance },
  { solutionPatternId: SP.payrollInfra,      problemId: P.employeeBenefits,
    confidence: "medium", notes: "Secondary — benefits is a common adjacency, not the primary problem." },
  { solutionPatternId: SP.cloudHcm,          problemId: P.wageCompliance },
  { solutionPatternId: SP.globalEmployment,  problemId: P.crossBorderEmploy },
  { solutionPatternId: SP.compoundWorkforce, problemId: P.wageCompliance },
  { solutionPatternId: SP.compoundWorkforce, problemId: P.itProvisioning },
  { solutionPatternId: SP.compoundWorkforce, problemId: P.crossBorderEmploy },
];

// ─────────────────────────────────────────────────────────────────────────────
// BOUNDARY CASE CATALOG
// ─────────────────────────────────────────────────────────────────────────────

export const BOUNDARY_CASES: NewBoundaryCase[] = [
  {
    companyName: "Rippling",
    optionA: "IP-002 (cloud-native SMB payroll SaaS)",
    optionB: "IP-005 (compound HR+IT+Finance platform)",
    chosen: "IP-005 (compound HR+IT+Finance platform)",
    reason: "Rippling's core value proposition is the unified Employee Graph enabling cross-functional automation — payroll is the wedge, not the thesis. Gusto is the canonical IP-002 instantiation.",
  },
  {
    companyName: "Zenefits",
    optionA: "IP-002 (cloud-native SMB payroll SaaS)",
    optionB: "IP-004 (compliance-led free HR SaaS, broker revenue)",
    chosen: "IP-004 (compliance-led free HR SaaS, broker revenue)",
    reason: "Zenefits mechanism was insurance broker commissions funding free software — structurally distinct from standard PEPM SaaS. The revenue model difference is the analytically important fact.",
  },
  {
    companyName: "Justworks",
    optionA: "IP-002 (cloud-native SMB payroll SaaS)",
    optionB: "IP-006 (global payroll / EOR platform)",
    chosen: "IP-002 (cloud-native SMB payroll SaaS, PEO variant)",
    reason: "Justworks PEO model is co-employment within the US, not cross-border employment. Conceptually closer to domestic outsourcing than international EOR.",
  },
  {
    companyName: "Deel (US payroll launch 2024)",
    optionA: "Keep as IP-006 only",
    optionB: "Add IP-002 relationship for US payroll",
    chosen: "Keep as IP-006 only, with note on company record and timeline",
    reason: "US payroll is a new expansion move for Deel, not its primary instantiation. Adding IP-002 would imply equivalence with Gusto — Deel US payroll is a secondary product, not its founding pattern.",
  },
  {
    companyName: "Papaya Global vs. Deel/Remote",
    optionA: "All three as IP-006 with no distinction",
    optionB: "Split into IP-006a (entity-ownership) and IP-006b (partner model)",
    chosen: "All three as IP-006, with sub-model recorded in notes",
    reason: "Partner vs. entity-ownership distinction is meaningful but not yet supported by enough evidence to justify a separate pattern record. If entity-ownership dominance confirmed across 3+ more observations, split warranted in Phase 2.",
  },
];